name: personal_finance
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  sqflite: ^2.0.0
  path: ^1.8.0
  fl_chart: ^0.70.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  local_auth: ^2.1.6
  shared_preferences: ^2.1.1
  csv: ^5.0.1
  path_provider: ^2.0.15
  provider: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

 